### ISSUE TITLE
Updater isn't working.

### ISSUE THREAD

**Issue by diggly** [Themaister/RetroArch-Phoenix#15]
The updater is not working. The list is empty.
I've asked a few other people and they're having the same problem.

**Comment by Themaister** [comment]
The latest file is suddenly empty, I don't know who did that.

**Comment by diggly** [comment]
Now I'm getting a "Download was not completed!" error when I try to update

**Comment by Themaister** [comment]
The updater has been purged. It won't come back. See this thread: http://forum.themaister.net/viewtopic.php?id=945
