### ISSUE TITLE
cheats window

### ISSUE THREAD

**Issue by eadmaster** [Themaister/RetroArch-Phoenix#2]
we need to add a window to interactively select cheats and generate the "cheat.cfg".

**Comment by Themaister** [comment]
This is a bit specific, and I think it's implemented by SSNES already. Sounds like a lot of work for little gain, however, I'll glady merge if someone does implement it. SSNES does save the current state of which cheats are selected, so cheats can be set in-game. To activate that you can set the "Cheat settings path", or so.
