### ISSUE TITLE
Segmentation fault with torrentzipped files. / adding .md support.

### ISSUE THREAD

**Issue by almostalive** [Themaister/RetroArch-Phoenix#3]
roms that have been compressed with torrentzip crashes ssnes-phoenix. On linux the terminal says "Segmentation fault". CMD in windows didn't say anything just crashed.

also could you add ".md",  to line 844 of ssnes-phoenix.cpp so the Genesis games with that extension can be extracted.

**Comment by Themaister** [comment]
I added .md. However, about this torrentzipped file. Is this a non-standard zip format or something? I use nall::zip for unzipping at least.

**Comment by almostalive** [comment]
since I forgot to close this. could you also add  .mdx .sms .gg and .sg that should cover all of the genesis-next stuff for decompressing. after that, that should be all there is for this issue. :) thanks to Dullaron for pointing the others out.

**Comment by Themaister** [comment]
LexSfx opened a pull request for that, so I'll consider it done. For minor stuff like this I suggest doing that if similar requests pop up later.
