### ISSUE TITLE
FFmpeg Green Screen

### ISSUE THREAD

**Issue by nyanpasu64** [Themaister/RetroArch-Phoenix#5]
WHen I record in FFmpeg at 256x224, I get a green mkv file with a glitchy light green line.

**Comment by Themaister** [comment]
This sounds like outdated version of FFmpeg or your player. Please paste relevant information about FFmpeg version on your system, media player used. Also, unless the .mkv is really big, please upload it somewhere as well.

**Comment by nyanpasu64** [comment]
WHat ffmpeg? Does it come with Phoenix? And if not, do I have to get it separately?

**Comment by Themaister** [comment]
Oh, right. I guess you're running on Windows? If so, then never mind, because I know which FFmpeg library is bundled with RetroArch (FFmpeg does the encoding stuff). I still need to know your media player, however.

**Comment by nyanpasu64** [comment]
VLC. Audio works, but I still get a green screen. I need to put out a video sometime, but ZSNES sucks, BSNES has no screen recorder, and SNES9X has a weird diagonal glitch, and I don't really want to use a screen recorder.

**Comment by Themaister** [comment]
I think VLC doesn't properly support H264/RGB yet. You can disable H264 and use the more stable FFV1 in Settings ->General->Disable H.264 recording. The encodings will be larger, but I guess that's not a big problem. That should be playable.

**Comment by nyanpasu64** [comment]
Still greenscreen of death. I tried restarting RetroArch.
Plus, how am I supposed to specify dimensions? Like 256x224?

**Comment by Themaister** [comment]
In the dimensions field to the right of ffmpeg output path selection, write 256x224.
Anyways, if you are still getting green screen even with FFV1, I need you to upload the .mkv.

In VLC 2.0 at least, FFV1 clips work, but H264/RGB is indeed green screen. Works fine in MPlayer at least, however.

**Comment by nyanpasu64** [comment]
Here: http://bin.smwcentral.net/u/17341/random_movie.mkv

**Comment by Themaister** [comment]
Video seems to work here in MPlayer: http://imgur.com/7jv3t
Interestingly enough, it doesn't work in VLC as you say :(

**Comment by nyanpasu64** [comment]
Well, WMP doesn't support mkv, so what do I use?

**Comment by Themaister** [comment]
Lossless output isn't something you'd distribute directly anyways. If you plan on putting it up on the net, I'd suggest looking into either FFmpeg or AVISynth to encode it into something more friendly. I think tasvideos.org should have some good tutorials on how to encode video game material. With FFV1 and DirectShow codecs you might get away with simple remuxing to .mp4 or maybe even .avi, but I haven't tested that.
