### ISSUE TITLE
Input bind list shouldn't scroll back after assignment

### ISSUE THREAD

**Issue by Jalle19** [Themaister/RetroArch-Phoenix#6]
Under "Input settings", if you scroll to the bottom of the list (e.g. to bind the analog stick) and bind a button, the list is immediately scrolled to the top again. This gets a bit frustrating after a while.

Ideally the list of bindings should flow with the window the window is resized, this way the scrollbar would disappear on reasonably high-res screens.

**Comment by Themaister** [comment]
Both issues are related to how Phoenix does things. I might be able to work around it at some later time.

**Comment by Themaister** [comment]
Scrolling issue is fixed. Resizing issue cannot be fixed at this time as Phoenix appears to have a bug related to automatic sizing inside containers.
