### ISSUE TITLE
Controller type gets reset to Gamepad after setting it to DualAnalog

### ISSUE THREAD

**Issue by Jalle19** [Themaister/RetroArch-Phoenix#7]
When I try setting the controller type to DualAnalog on port 1 and 2 and close RetroArch, the settings seem to be forgotten cause when I launch it again the type is still Gamepad.

**Comment by Themaister** [comment]
The GUI currently doesn't save this information to the config. This will be added at a later time.

**Comment by Themaister** [comment]
Fixed now.
