### ISSUE TITLE
Revert to default key binding

### ISSUE THREAD

**Issue by MrXCuci** [Themaister/RetroArch-Phoenix#9]
Using this option for the controls your are setting up at that moment dos not work. If you click "default all" and in the dialog screen you press No. Settings revert anyway. 0.98 Windows xp 64

**Comment by Themaister** [comment]
Intended behavior, it asks if you want to default settings in other drop down menus as well. E.g. in Player 1, Default All will default all in Player 1, and all the others if you pick yes.

**Comment by MrXCuci** [comment]
Ok, but why the dialog with the option YES / NO when using default all. If you press NO, it reverts anyway. Clicking the button "default" doesn't do anything. I suppose this should work in the thing you are configuring at the moment.

**Comment by Themaister** [comment]
Default defaults the button you have selected only. Default All, is as the name implies designed to default everything. Default All asks you if you want to delete binds on other pages as well.
